quiz/config/routes.rb
Quiz::Application.routes.draw do

  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    get '/login' => 'devise/sessions#new', as: :login
    get '/logout' => 'sessions#destroy', :as => :logout
    get '/signup' => 'registrations#new', :as => :signup
    scope 'my' do
      get 'profile', to: 'registrations#edit'
      put 'profile/update', to: 'registrations#update'
      get 'password/edit', to: 'registrations#edit_password'
      put 'password/update', to: 'registrations#update_password'
    end
  end

  unauthenticated do
    get '/logout' => redirect('/')
  end

  authenticate :user, ->(u) { u.super_admin? } do
    get '/delayed_job' => DelayedJobWeb, :anchor => false
    put '/delayed_job' => DelayedJobWeb, :anchor => false
    post '/delayed_job' => DelayedJobWeb, :anchor => false

    ActiveAdmin.routes(self)
    namespace :superadmin do
      root to: 'users#index'
      resources :users
    end

  end

  get 'pages/about'
  get 'pages/contact_us'
  resources :contacts, only: [:create]

  authenticated :user do
    get '/pages' => 'pages#index', as: :pages
  end

  unauthenticated do
    as :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_scope :user do
        post 'login' => 'sessions#create', as: 'login'
      end

      resources :users, only: [:show, :create, :update, :destroy], constraints: { id: /.*/ }
    end
  end

  root 'home#index'
end

quiz/app/views/shared/_modal.html.haml
%div{class: "modal", "data-behavior" => "modal-content"}
  .modal-dialog
    .modal-content
      .modal-header
        = button_tag '×', :class => "close btn-close-dialog", "data-behavior" => "modal-close", "aria-hidden" => "true"
        %h4.modal-title= yield(:modal_title)
      .modal-body
        = yield(:modal_body)

quiz/app/views/shared/_nav.html.haml
%ul.nav.navbar-nav
  = nav_link 'Home', root_path
  = nav_link 'About', pages_about_path
  = nav_link 'Contact us', pages_contact_us_path
= render('shared/user_right_nav')

quiz/app/views/shared/_superadmin_nav.html.haml
%ul.nav.navbar-nav
  = nav_link('Users', superadmin_users_path)
  = nav_link("Active Admin", active_admin_root_path)
  = nav_link('DJ', '/delayed_job', false, "target" => '_blank')
= render('shared/user_right_nav')

quiz/app/views/shared/_user_is_signed_in.html.haml
%li.dropdown
  %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    = current_user.name
    %b.caret
  %ul.dropdown-menu
    - if super_admin_signed_in?
      = nav_link 'Superadmin', superadmin_root_path
      %li.divider
    = nav_link 'My account', profile_path
    = nav_link 'Change password', password_edit_path
    = nav_link 'Logout', destroy_user_session_path, false, method: :delete

quiz/app/views/shared/_user_right_nav.html.haml
%ul.nav.navbar-nav.navbar-right
  - if user_signed_in?
    = render 'shared/user_is_signed_in'
  - else
    = nav_link 'Sign in', new_session_path(:user)